version: "3.8"

services:

  postgresql:
    container_name: dbzpostgresql
    image: debezium/postgres
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgre_volume:/var/lib/postgresql/data

  pgadmin:
    container_name: dbzpgadmin4
    image: dpage/pgadmin4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  kafka:
    container_name: dbzkafka
    image: confluentinc/cp-kafka:latest
    restart: "no"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    container_name: dbzzookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: "no"
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafdrop:
    container_name: dbzkafdrop
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: -Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify

  kafkaconnect:
    container_name: dbzkafkaconnect
    image: debezium/connect:1.7.0.Final
    restart: "no"
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - postgresql
      - mongodb
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:29092
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses



volumes:
  postgre_volume:
